python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 2 --o 2 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 2 --o 3 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 2 --o 4 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 2 --o 5 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 3 --o 2 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 3 --o 3 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 3 --o 4 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 3 --o 5 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 4 --o 2 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 4 --o 3 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 4 --o 4 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 4 --o 5 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 5 --o 2 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 5 --o 3 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 5 --o 4 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 5 --o 5 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 6 --o 2 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 6 --o 3 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 6 --o 4 &&
python3 main.py --hypergraph ./datasets/congress/network.hyp --digraph ./datasets/congress/network.dir --algorithm ko --k 6 --o 5 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 2 --o 2 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 2 --o 3 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 2 --o 4 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 2 --o 5 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 3 --o 2 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 3 --o 3 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 3 --o 4 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 3 --o 5 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 4 --o 2 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 4 --o 3 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 4 --o 4 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 4 --o 5 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 5 --o 2 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 5 --o 3 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 5 --o 4 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 5 --o 5 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 6 --o 2 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 6 --o 3 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 6 --o 4 &&
python3 main.py --hypergraph ./datasets/chameleon/network.hyp --digraph ./datasets/chameleon/network.dir --algorithm ko --k 6 --o 5 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 2 --o 2 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 2 --o 3 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 2 --o 4 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 2 --o 5 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 3 --o 2 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 3 --o 3 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 3 --o 4 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 3 --o 5 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 4 --o 2 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 4 --o 3 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 4 --o 4 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 4 --o 5 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 5 --o 2 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 5 --o 3 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 5 --o 4 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 5 --o 5 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 6 --o 2 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 6 --o 3 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 6 --o 4 &&
python3 main.py --hypergraph ./datasets/gowalla/network.hyp --digraph ./datasets/gowalla/network.dir --algorithm ko --k 6 --o 5 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 2 --o 2 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 2 --o 3 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 2 --o 4 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 2 --o 5 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 3 --o 2 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 3 --o 3 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 3 --o 4 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 3 --o 5 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 4 --o 2 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 4 --o 3 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 4 --o 4 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 4 --o 5 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 5 --o 2 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 5 --o 3 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 5 --o 4 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 5 --o 5 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 6 --o 2 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 6 --o 3 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 6 --o 4 &&
python3 main.py --hypergraph ./datasets/meetup/network.hyp --digraph ./datasets/meetup/network.dir --algorithm ko --k 6 --o 5